### Copyright 2025-2026 JKLeckr
### SPDX-License-Identifier: MPL-2.0

from ...names import regionnames

levels: set[str] = {
    regionnames.level_boss_veggies,
    regionnames.level_boss_slime,
    regionnames.level_boss_frogs,
    regionnames.level_boss_flower,
    regionnames.level_boss_baroness,
    regionnames.level_boss_clown,
    regionnames.level_boss_dragon,
    regionnames.level_boss_bee,
    regionnames.level_boss_pirate,
    regionnames.level_boss_mouse,
    regionnames.level_boss_sallystageplay,
    regionnames.level_boss_train,
    regionnames.level_boss_plane_blimp,
    regionnames.level_boss_plane_genie,
    regionnames.level_boss_plane_bird,
    regionnames.level_boss_plane_mermaid,
    regionnames.level_boss_plane_robot,
    regionnames.level_boss_kingdice,
    regionnames.level_boss_devil,
    regionnames.level_dicepalace_boss_booze,
    regionnames.level_dicepalace_boss_chips,
    regionnames.level_dicepalace_boss_cigar,
    regionnames.level_dicepalace_boss_domino,
    regionnames.level_dicepalace_boss_rabbit,
    regionnames.level_dicepalace_boss_plane_horse,
    regionnames.level_dicepalace_boss_roulette,
    regionnames.level_dicepalace_boss_eightball,
    regionnames.level_dicepalace_boss_plane_memory,
    regionnames.level_rungun_forest,
    regionnames.level_rungun_tree,
    regionnames.level_rungun_circus,
    regionnames.level_rungun_funhouse,
    regionnames.level_rungun_harbour,
    regionnames.level_rungun_mountain,
    regionnames.level_dlc_boss_oldman,
    regionnames.level_dlc_boss_rumrunners,
    regionnames.level_dlc_boss_snowcult,
    regionnames.level_dlc_boss_airplane,
    regionnames.level_dlc_boss_plane_cowboy,
    regionnames.level_dlc_boss_saltbaker,
    regionnames.level_dlc_graveyard,
    regionnames.level_dlc_chesscastle_pawn,
    regionnames.level_dlc_chesscastle_knight,
    regionnames.level_dlc_chesscastle_bishop,
    regionnames.level_dlc_chesscastle_rook,
    regionnames.level_dlc_chesscastle_queen,
    regionnames.level_dlc_chesscastle_run,
}
