### Copyright 2025-2026 JKLeckr
### SPDX-License-Identifier: MPL-2.0

from ...names import locationnames

levels: set[str] = {
    locationnames.level_boss_veggies,
    locationnames.level_boss_slime,
    locationnames.level_boss_frogs,
    locationnames.level_boss_flower,
    locationnames.level_boss_baroness,
    locationnames.level_boss_clown,
    locationnames.level_boss_dragon,
    locationnames.level_boss_bee,
    locationnames.level_boss_pirate,
    locationnames.level_boss_mouse,
    locationnames.level_boss_sallystageplay,
    locationnames.level_boss_train,
    locationnames.level_boss_plane_blimp,
    locationnames.level_boss_plane_genie,
    locationnames.level_boss_plane_bird,
    locationnames.level_boss_plane_mermaid,
    locationnames.level_boss_plane_robot,
    locationnames.level_boss_kingdice,
    locationnames.level_boss_devil,
    locationnames.level_dicepalace_boss_booze,
    locationnames.level_dicepalace_boss_chips,
    locationnames.level_dicepalace_boss_cigar,
    locationnames.level_dicepalace_boss_domino,
    locationnames.level_dicepalace_boss_rabbit,
    locationnames.level_dicepalace_boss_plane_horse,
    locationnames.level_dicepalace_boss_roulette,
    locationnames.level_dicepalace_boss_eightball,
    locationnames.level_dicepalace_boss_plane_memory,
    locationnames.level_rungun_forest,
    locationnames.level_rungun_tree,
    locationnames.level_rungun_circus,
    locationnames.level_rungun_funhouse,
    locationnames.level_rungun_harbour,
    locationnames.level_rungun_mountain,
    locationnames.level_dlc_boss_oldman,
    locationnames.level_dlc_boss_rumrunners,
    locationnames.level_dlc_boss_snowcult,
    locationnames.level_dlc_boss_airplane,
    locationnames.level_dlc_boss_plane_cowboy,
    locationnames.level_dlc_boss_saltbaker,
    locationnames.level_dlc_graveyard,
    locationnames.level_dlc_chesscastle_pawn,
    locationnames.level_dlc_chesscastle_knight,
    locationnames.level_dlc_chesscastle_bishop,
    locationnames.level_dlc_chesscastle_rook,
    locationnames.level_dlc_chesscastle_queen,
    locationnames.level_dlc_chesscastle_run,
}
