# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
lint.select = ["E", "F", "W", "B", "C901"]
lint.ignore = ["E501"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = ["B", "C901"]

# Exclude a variety of commonly ignored directories.
extend-exclude = [
    "**/__pycache__",
    "scriptstash.py",
]

# Cache dir outside of .github
cache-dir = "../.ruff_cache"

# Assume Python 3.10
target-version = "py310"
