Cuphead:
  fuzz_constraints:
    - option: filler_weight_extrahealth
      if_value: 0
      then:
        filler_weight_supercharge: 1
    - option: trap_weight_fingerjam
      if_value: 0
      then:
        trap_weight_slowfire: 1
    - option: accessibility
      if_value: minimal
      then:
        randomize_abilities: "false"
        weapon_mode: normal
        boss_grade_checks: disabled
        rungun_grade_checks: disabled
        silverworth_quest: "false"
        pacifist_quest: "false"
        dlc_boss_chalice_checks: disabled
        dlc_rungun_chalice_checks: disabled
        dlc_kingdice_chalice_checks: disabled
        dlc_chess_chalice_checks: disabled
        dlc_cactusgirl_quest: "false"
        extra_coins: 0
    - option: use_dlc
      if_value: "false"
      then:
        dlc_chalice: disabled
        dlc_curse_mode: "off"
        dlc_kingsleap: exclude
        dlc_boss_chalice_checks: disabled
        dlc_rungun_chalice_checks: disabled
        dlc_kingdice_chalice_checks: disabled
        dlc_chess_chalice_checks: disabled
        dlc_cactusgirl_quest: "false"
    - option: start_weapon
      if_value: none
      then:
        logic_mode: hard
        randomize_abilities: "false"
