from __future__ import annotations
from ..names import LocationNames

level_ids: dict[int, str] = {
    0: LocationNames.level_boss_veggies,
    1: LocationNames.level_boss_slime,
    2: LocationNames.level_boss_frogs,
    3: LocationNames.level_boss_flower,
    4: LocationNames.level_boss_baroness,
    5: LocationNames.level_boss_clown,
    6: LocationNames.level_boss_dragon,
    7: LocationNames.level_boss_bee,
    8: LocationNames.level_boss_pirate,
    9: LocationNames.level_boss_mouse,
    10: LocationNames.level_boss_sallystageplay,
    11: LocationNames.level_boss_train,
    12: LocationNames.level_boss_plane_blimp,
    13: LocationNames.level_boss_plane_genie,
    14: LocationNames.level_boss_plane_bird,
    15: LocationNames.level_boss_plane_mermaid,
    16: LocationNames.level_boss_plane_robot,
    17: LocationNames.level_boss_kingdice,
    18: LocationNames.level_boss_devil,
    19: LocationNames.level_dicepalace_boss_booze,
    20: LocationNames.level_dicepalace_boss_chips,
    21: LocationNames.level_dicepalace_boss_cigar,
    22: LocationNames.level_dicepalace_boss_domino,
    23: LocationNames.level_dicepalace_boss_rabbit,
    24: LocationNames.level_dicepalace_boss_plane_horse,
    25: LocationNames.level_dicepalace_boss_roulette,
    26: LocationNames.level_dicepalace_boss_eightball,
    27: LocationNames.level_dicepalace_boss_plane_memory,
    28: LocationNames.level_rungun_forest,
    29: LocationNames.level_rungun_tree,
    30: LocationNames.level_rungun_circus,
    31: LocationNames.level_rungun_funhouse,
    32: LocationNames.level_rungun_harbour,
    33: LocationNames.level_rungun_mountain,
    100: LocationNames.level_dlc_boss_oldman,
    101: LocationNames.level_dlc_boss_rumrunners,
    102: LocationNames.level_dlc_boss_snowcult,
    103: LocationNames.level_dlc_boss_airplane,
    104: LocationNames.level_dlc_boss_plane_cowboy,
    105: LocationNames.level_dlc_boss_saltbaker,
    106: LocationNames.level_dlc_graveyard,
    107: LocationNames.level_dlc_chesscastle_pawn,
    108: LocationNames.level_dlc_chesscastle_knight,
    109: LocationNames.level_dlc_chesscastle_bishop,
    110: LocationNames.level_dlc_chesscastle_rook,
    111: LocationNames.level_dlc_chesscastle_queen,
    112: LocationNames.level_dlc_chesscastle_run,
}
level_to_id = {v: k for k, v in level_ids.items()}
