### Copyright 2025-2026 JKLeckr
### SPDX-License-Identifier: MPL-2.0

from __future__ import annotations

from ..names import regionnames

level_ids: dict[int, str] = {
    0: regionnames.level_boss_veggies,
    1: regionnames.level_boss_slime,
    2: regionnames.level_boss_frogs,
    3: regionnames.level_boss_flower,
    4: regionnames.level_boss_baroness,
    5: regionnames.level_boss_clown,
    6: regionnames.level_boss_dragon,
    7: regionnames.level_boss_bee,
    8: regionnames.level_boss_pirate,
    9: regionnames.level_boss_mouse,
    10: regionnames.level_boss_sallystageplay,
    11: regionnames.level_boss_train,
    12: regionnames.level_boss_plane_blimp,
    13: regionnames.level_boss_plane_genie,
    14: regionnames.level_boss_plane_bird,
    15: regionnames.level_boss_plane_mermaid,
    16: regionnames.level_boss_plane_robot,
    17: regionnames.level_boss_kingdice,
    18: regionnames.level_boss_devil,
    19: regionnames.level_dicepalace_boss_booze,
    20: regionnames.level_dicepalace_boss_chips,
    21: regionnames.level_dicepalace_boss_cigar,
    22: regionnames.level_dicepalace_boss_domino,
    23: regionnames.level_dicepalace_boss_rabbit,
    24: regionnames.level_dicepalace_boss_plane_horse,
    25: regionnames.level_dicepalace_boss_roulette,
    26: regionnames.level_dicepalace_boss_eightball,
    27: regionnames.level_dicepalace_boss_plane_memory,
    28: regionnames.level_rungun_forest,
    29: regionnames.level_rungun_tree,
    30: regionnames.level_rungun_circus,
    31: regionnames.level_rungun_funhouse,
    32: regionnames.level_rungun_harbour,
    33: regionnames.level_rungun_mountain,
    100: regionnames.level_dlc_boss_oldman,
    101: regionnames.level_dlc_boss_rumrunners,
    102: regionnames.level_dlc_boss_snowcult,
    103: regionnames.level_dlc_boss_airplane,
    104: regionnames.level_dlc_boss_plane_cowboy,
    105: regionnames.level_dlc_boss_saltbaker,
    106: regionnames.level_dlc_graveyard,
    107: regionnames.level_dlc_chesscastle_pawn,
    108: regionnames.level_dlc_chesscastle_knight,
    109: regionnames.level_dlc_chesscastle_bishop,
    110: regionnames.level_dlc_chesscastle_rook,
    111: regionnames.level_dlc_chesscastle_queen,
    112: regionnames.level_dlc_chesscastle_run,
}
level_to_id = {v: k for k, v in level_ids.items()}
