### Copyright 2025-2026 JKLeckr
### SPDX-License-Identifier: MPL-2.0

from __future__ import annotations

from ..names import locationnames

level_ids: dict[int, str] = {
    0: locationnames.level_boss_veggies,
    1: locationnames.level_boss_slime,
    2: locationnames.level_boss_frogs,
    3: locationnames.level_boss_flower,
    4: locationnames.level_boss_baroness,
    5: locationnames.level_boss_clown,
    6: locationnames.level_boss_dragon,
    7: locationnames.level_boss_bee,
    8: locationnames.level_boss_pirate,
    9: locationnames.level_boss_mouse,
    10: locationnames.level_boss_sallystageplay,
    11: locationnames.level_boss_train,
    12: locationnames.level_boss_plane_blimp,
    13: locationnames.level_boss_plane_genie,
    14: locationnames.level_boss_plane_bird,
    15: locationnames.level_boss_plane_mermaid,
    16: locationnames.level_boss_plane_robot,
    17: locationnames.level_boss_kingdice,
    18: locationnames.level_boss_devil,
    19: locationnames.level_dicepalace_boss_booze,
    20: locationnames.level_dicepalace_boss_chips,
    21: locationnames.level_dicepalace_boss_cigar,
    22: locationnames.level_dicepalace_boss_domino,
    23: locationnames.level_dicepalace_boss_rabbit,
    24: locationnames.level_dicepalace_boss_plane_horse,
    25: locationnames.level_dicepalace_boss_roulette,
    26: locationnames.level_dicepalace_boss_eightball,
    27: locationnames.level_dicepalace_boss_plane_memory,
    28: locationnames.level_rungun_forest,
    29: locationnames.level_rungun_tree,
    30: locationnames.level_rungun_circus,
    31: locationnames.level_rungun_funhouse,
    32: locationnames.level_rungun_harbour,
    33: locationnames.level_rungun_mountain,
    100: locationnames.level_dlc_boss_oldman,
    101: locationnames.level_dlc_boss_rumrunners,
    102: locationnames.level_dlc_boss_snowcult,
    103: locationnames.level_dlc_boss_airplane,
    104: locationnames.level_dlc_boss_plane_cowboy,
    105: locationnames.level_dlc_boss_saltbaker,
    106: locationnames.level_dlc_graveyard,
    107: locationnames.level_dlc_chesscastle_pawn,
    108: locationnames.level_dlc_chesscastle_knight,
    109: locationnames.level_dlc_chesscastle_bishop,
    110: locationnames.level_dlc_chesscastle_rook,
    111: locationnames.level_dlc_chesscastle_queen,
    112: locationnames.level_dlc_chesscastle_run,
}
level_to_id = {v: k for k, v in level_ids.items()}
