name: LintCheck

on:
  pull_request:
    paths:
      - "**.py"
      - ".github/ruff.toml"
      - ".github/ruff_check.py"
      - ".github/workflows/lint-check.yml"
  push:
    paths:
      - "**.py"
      - ".github/ruff.toml"
      - ".github/ruff_check.py"
      - ".github/workflows/lint-check.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Archipelago/

    steps:
      - name: Checkout Archipelago
        uses: actions/checkout@v4
        with:
          repository: JKLeckr/Archipelago
          path: Archipelago
          ref: base

      - name: Checkout Cuphead
        uses: actions/checkout@v4
        with:
          path: Archipelago/worlds/cuphead

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip ruff==0.11.10
          python ModuleUpdate.py --append "WebHostLib/requirements.txt" --force --yes

      - name: "Run ruff"
        working-directory: Archipelago/worlds/cuphead
        run: ruff --config ./ruff.toml check
