name: TagRelease

on:
  push:
    tags:
      - '*'
      - '!*test*'

jobs:
  create-build-release:
    name: Create, Build, and Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0  # Fetch all history for possible versioning

      - name: Clean project directory
        run: |
          # Move examples dir out as it is not needed in the apworld
          mv examples ..
          # Remove unnecessary files and directories
          find . -type d -name "__pycache__" -exec rm -rf {} \; 2>/dev/null
          find . -type d -name ".ruff_cache" -exec rm -rf {} \; 2>/dev/null
          rm -rf .git .github .gitignore
          rm -rf extras
          rm -f ruff.toml

      - name: Build ZIP package
        working-directory: ../
        run: |
          mv Archipelago-cuphead cuphead
          zip -r cuphead.zip cuphead -x "*.git*" "*.github*" "*_pycache_*" "examples/" "*.ruff_cache*"
          mv cuphead Archipelago-cuphead
          mv cuphead.zip cuphead.apworld

      - name: Calculate SHA256 checksum
        working-directory: ../
        run: |
          sha256sum cuphead.apworld > cuphead.apworld.sha256

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          name: Preview (${{ env.RELEASE_VERSION }})
          token: ${{ secrets.AP_TOKEN }}
          files: |
            ../cuphead.apworld
            ../cuphead.apworld.sha256
            ../examples/*
