### Copyright 2025-2026 JKLeckr
### SPDX-License-Identifier: MPL-2.0

name: TagRelease

on:
  push:
    tags:
      - "*"
      - "!*norel*"

jobs:
  create-build-release:
    name: Create, Build, and Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0  # Fetch all history for possible versioning

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Clean project directory
        run: |
          # Move examples dir and genapjson out as they are not needed in the apworld
          mv examples ..
          mv scripts/genapjson.py ..
          # Remove unnecessary files and directories
          find . -type d -name "__pycache__" -exec rm -rf {} \; 2>/dev/null
          find . -type d -name ".ruff_cache" -exec rm -rf {} \; 2>/dev/null
          rm -rf .git .github .gitignore
          rm -rf extras
          rm -rf scripts
          rm -f ruff.toml
          rm -f pyrightconfig.json

      - name: Generate archipelago.json
        working-directory: ../
        run: |
          export SIMPLE_VERSION=$(printf '%s\n' "${{ env.RELEASE_VERSION }}" | sed 's/\.[0-9]\+//')
          python ./genapjson.py -o ./archipelago.json ./Archipelago-cuphead/__init__.py -m ${SIMPLE_VERSION}

      - name: Build ZIP package
        working-directory: ../
        run: |
          mv Archipelago-cuphead cuphead
          zip -r cuphead.zip archipelago.json cuphead -x "*.git*" "*.github*" "*_pycache_*" "examples/" "*.ruff_cache*" "genapjson.py"
          mv cuphead Archipelago-cuphead
          mv cuphead.zip cuphead.apworld

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: APWorld ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.AP_TOKEN }}
          files: |
            ../cuphead.apworld
            ../examples/*
